### ISSUE TITLE
Bug: unrecognized keyword: 'key'

### ISSUE THREAD

**Issue by abhisheksp** [DistAlgo/distalgo#11]
[dist_algo_max_bug.txt](https://github.com/DistAlgo/distalgo/files/1420410/dist_algo_max_bug.txt)
Error Message:
error: malformed max statement: unrecognized keyword: 'key'.

Attached code example

**Comment by sadboy** [comment]
Thanks for reporting! This should be fixed in version `1.0.10` (if you're using `pip`, just `pip install --upgrade pydistalgo`)

**Comment by abhisheksp** [comment]
Thanks, Closing Issue
