### ISSUE TITLE
If await statements seem to be deterministic

### ISSUE THREAD

**Issue by AlexisGrall** [DistAlgo/distalgo#13]
Contrary to what the doc says, an if await statement seems to always choose the first branch for which the conditions are satisfied.
See example below.
[ifawait.txt](https://github.com/DistAlgo/distalgo/files/2110556/ifawait.txt)

**Comment by yanhongliu** [comment]
Yes, the implementation so far tests the branches in order.  It has not been any problem for all practical programming we've seen, but we know of some need of nondeterminism for theoretical studies, and we have a plan to add that.  For now, you could program your conditions manually together with some randomness.   I wonder what's your need in particular.

**Comment by AlexisGrall** [comment]
It is not really a problem for my use.
I was only surprised the doc is not telling it. Reading the doc, I assumed it was non-deterministic.

**Comment by yanhongliu** [comment]
Nondeterminism means that any order might be used and all should be ok, and doing in order of appearance is common in practice.  We didn't want to say that order about the implementation, because we want to avoid people actually using it.  We will revisit this when we see more/practical uses.
