### ISSUE TITLE
pseudo.py incorrectly prepends "self" to some variables in receive patterns

### ISSUE THREAD

**Issue by scottstoller** [DistAlgo/distalgo#17]
da/examples/dscrash/orig.da contains:

    def receive(msg=('Value', v)):
       receiveflag = True
       if v not in V:
             V[v] = False

pseudo.py prints the variable in the receive pattern as self.v.  it should be printed as v not self.v, because it is not preceded by '=' and hence is a procedure-local pattern variable.

**Comment by sadboy** [comment]
This should also be fixed on master. Thanks for reporting this!
