### ISSUE TITLE
ImportError with Python 3.7.0

### ISSUE THREAD

**Issue by jmnotin** [DistAlgo/distalgo#18]
Hi,

Running DistAlgo using Python 3.7.0 raises the following `ImportError`:

~~~
ImportError: cannot import name '_validate_bytecode_header' from 'importlib._bootstrap_external' (/usr/lib/python3.7/importlib/_bootstrap_external.py)
~~~

It appears that `importer.py` is using internal functions (one is `_validate_bytecode_header`) from `importlib._bootstrap_external` that were removed for 3.7.0 by [this commit](https://github.com/python/cpython/commit/42aa93b8ff2f7879282b06efc73a31ec7785e602).

Regards,

**Comment by sadboy** [comment]
Fixed on master, thanks for reporting!
