### ISSUE TITLE
failure in all 4 options of installation DistAlgo

### ISSUE THREAD

**Issue by lmarne01** [DistAlgo/distalgo#29]
I tried all 4 options in the readme.md file for installing distAlgo in both windows and linux and all resulted in the same error:
python -m da.compiler some_path\distalgo-master\da\examples\2pcommit\_init_.py:
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python35\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "some_path\distalgo-master\da\__init__.py", line 3, in <module>
    from . import common
  File "some_path\distalgo-master\da\common.py", line 149
    msg = (f'This system is configured to use "{hostname}" as its fully '
                                                                        ^
SyntaxError: invalid syntax
looking at the error message in the file the texting is like this:
'This system is configured to use "{hostname}" as its fully '
                   'qualified domain name, but it is not resolvable. Please '
                   'specify a hostname or an IP address via the "--hostname"'
                   '(or equivalently "-H") command line argument. If you only '
                   'intend to connect to other DistAlgo nodes running on '
                   'this system, you can use "-H localhost". Otherwise, '
                   'you must specify a hostname or an IP address that is '
                   'reachable from remote hosts.'

I would like to know the correct syntax to run the examples given

**Comment by yanhongliu** [comment]
Hi, your error message suggests you are using Python 3.5, for which we are not actively maintaining.
You may try Python 3.6 and just do "pip install pyDistAlgo" as in option 1
or Python 3.7 and do "pip install --pre pyDistAlgo", also in option 1.

**Comment by lmarne01** [comment]
Hi, I have tried that before and had some errors but for some reason it worked now. Thank you!

**Comment by dheerajramchandani** [comment]
Hi,

I am using a conda environment with python 3.7.4. The command pip install pyDistAlgo failed and I gather from this post that I should be using pip install --pre pyDistAlgo but I do not understand it much from the description of this flag from README. It seems to me that --pre flag is used to install latest version which is not "stable". If it's not stable then what kinds of issues are expected in the latest version? Would you please be able to elaborate the use of --pre flag? I am using a clean conda environment.

Thanks.

**Comment by cottonty** [comment]
> Hi,
> 
> I am using a conda environment with python 3.7.4. The command pip install pyDistAlgo failed and I gather from this post that I should be using pip install --pre pyDistAlgo but I do not understand it much from the description of this flag from README. It seems to me that --pre flag is used to install latest version which is not "stable". If it's not stable then what kinds of issues are expected in the latest version? Would you please be able to elaborate the use of --pre flag? I am using a clean conda environment.
> 
> Thanks.

pip and conda install packages from different repositories, and since DistAlgo is not dependent by other modules currently, it won't break your conda environment by installing with pip install --pre.

**Comment by dheerajramchandani** [comment]
Ok, thanks.
