### ISSUE TITLE
communication between 2 programs in 2 terminals

### ISSUE THREAD

**Issue by lmarne01** [DistAlgo/distalgo#30]
I understand that in order for 2 terminals to communicate with each other, the same da file needs to run so that the class is accessible to both terminals. Also i understand that in the main of the da file it needs to create the process at the site to communicate with it. But ,to my knowledge,this cannot always be applied in real situations. Let's take the example from README.md

class Ping(process):
    def setup(pong): pass
    def run():
        send(('Ping',), to=pong)
        await(received(('Pong',)))
         output("Ponged.")
      
class Pong(process):
    def setup(): pass
    def run():
        await(some(received(('Ping',), from_=ping)))
        output("Pinged.")
        send(('Pong',), to=ping)
      
def main():
    pong = new(Pong, args=(), at='PongNode')
    ping = new(Ping, args=(pong,))
    start(pong)
    start(ping)

what I want to do is to have 2 separate da files running, something like this:

**ping.da:**
class Ping(process):
    def setup(pong): pass
    def run():
        send(('Ping',), to=pong)
        await(received(('Pong',)))
        output("Ponged.")
      
def main():
    ping = new(Ping, args=(pong,))
    start(ping)

**pong.da:**     
class Pong(process):
    def setup(): pass 
    def receive(msg=('Ping',),from_=ping):
        output("Pinged.")
        send(('Pong',), to=ping)

def main():
    pong = new(Pong, args=())
    start(pong)

is it possible in any way to achieve this? Please correct me if i'm wrong.

**Comment by yanhongliu** [comment]
Hi, your ping.da won't work because you use an undefined variable 'pong' in 'main'.  You will need the original da file.
However, you don't need to run the same file on both terminals: on the one where you run the pong process, you can use an empty da file.

**Comment by lmarne01** [comment]
I understood wrong the part about running the da files on terminals, thank you for clearing this up and sorry for the wrong example, but i still have some questions. I have created these 2 files to test message exchange between 2 processes in the same machine with 2 terminals:
**ping.da:**
```
class Ping(process):
    def setup(): pass
    def run():
        send(('Ping',),to='PongNode@local_address')
        output("send completed")
        await(received(('Pong',)))
          
def main():
    ping = new(Ping, args=())
    start(ping)
    await(False)
```

**pong.da:**
```
class Pong(process):
    def setup(): pass
    def run():
        await(received(('Ping',)))
        output('Pinged')
        send(('Pong',),to='PongNode')

def main():
    pong = new(Pong, args=())
    start(pong)
    await(False)
```

**local_address:** address of the machine
When i run these 2 programs in terminals i get the message `Bootstrap succeeded using <UdpTransport(local_address:port)>`, but it doesn't pass through the await line of pong.da, meaning that it didn't receive the message ('Ping',). Is it because i inserted 'PongNode@local_address' instead of a process? If that's the case is there a way for  2 processes (one from each terminal) to communicate without passing the destination process as an argument to the source process?

**Comment by yanhongliu** [comment]
Currently, two DistAlgo processes that want to communicate need to have a common ancestor in the process tree, so that one of them can get the address of the other either from setup or in a message.

**Comment by lmarne01** [comment]
i understand. thank you
