### ISSUE TITLE
independent communication between 2 processes

### ISSUE THREAD

**Issue by lmarne01** [DistAlgo/distalgo#31]
I have created these 2 files to test message exchange between 2 processes in the same machine with 2 terminals:
**ping.da:**
```
class Ping(process):
    def setup(): pass
    def run():
        send(('Ping',),to='PongNode@local_address')
        output("send completed")
        await(received(('Pong',)))
          
def main():
    ping = new(Ping, args=())
    start(ping)
    await(False)
```

**pong.da:**
```
class Pong(process):
    def setup(): pass
    def run():
        await(received(('Ping',)))
        output('Pinged')
        send(('Pong',),to='PongNode')

def main():
    pong = new(Pong, args=())
    start(pong)
    await(False)
```

**local_address:** address of the machine
When i run these 2 programs in terminals i get the message `Bootstrap succeeded using <UdpTransport(local_address:port)>`, but it doesn't pass through the await line of pong.da, meaning that it didn't receive the message ('Ping',). Is it because i inserted 'PongNode@local_address' in variable _to_ in ping.da instead of a process? If that's the case is there a way for  2 processes (one from each terminal) to communicate without passing the destination process as an argument to the source process?

**Comment by yanhongliu** [comment]
See answer to #30. 
Right, that string as the target of a message does not make sense.  It has to be a DistAlgo process.
