### ISSUE TITLE
Remote hosts

### ISSUE THREAD

**Issue by rlnd1** [DistAlgo/distalgo#34]
Hi,
I want to run a DistAlgo program on different hosts. As in the readme, I use the Ping pong example. In the main method, I added `at='PongNode@host1'` and `at='PingNode@host2'`
On host1, I started the node with `python3 -m da -n PingNode -H 0.0.0.0 pingpong.da` and then on host2 with `python3 -m da -n PongNode -H 0.0.0.0 -D pingpong.da`.
Then the following errors occur:
```
host1: BootstrapException('Unable to contact a peer node.',)
host2: WARNING: Exception when handling ('192.168.1.137', 47064): VersionMismatchException("Version from ('192.168.1.137', 54254) is different.",)
```
I use Ubuntu.
What does this mean? Did I forget something?

**Comment by scottstoller** [comment]
Hello!  DistAlgo doesn't accept 0.0.0.0 as an alias for the host's IP address.  Please try again using the host's actual IP address.  There are several ways to get the IP address on Linux; for example, run "ifconfig".

**Comment by ghanendrapiplani** [comment]
Hey @rlnd1
Were you able to figure out running on the different nodes part? We are planning to use distalgo too in multiple remote hosts, came across your issue..

**Comment by yanhongliu** [comment]
Hi, pls use the instruction in the current README; it's simpler and has been there/used for 3+ years.

(Sorry we missed the previous question for some reason. The old way could still work because the old code is still left in, but we want to move on to the simpler way.)

**Comment by scottstoller** [comment]
The simple instructions in the current README for running on multiple machines work on many systems, including AWS and Google Compute Engine.  On some machines, depending on the network configuration, you might still need to add "-H <IP-address-of-this-machine>" on the command line after "-m da".  We will try to automate this later so -H is never needed.
