### ISSUE TITLE
circular dependencies

### ISSUE THREAD

**Issue by lk-chen** [DistAlgo/distalgo#5]
I got the source file from sourceforge.

When I try to compile or run with executable file in /bin, python reported an ImportError in sim.py, saying "cannot find name api", which is caused by circular dependencies.

I have tried on both Ubuntu and Window 10.

After I remove the import of api in sim.py, it compiles and runs perfectly.

**Comment by lk-chen** [comment]
The file is correct in master branch, but wrong on sourceforge.

**Comment by sadboy** [comment]
Yes, 1.0.0b17 is broken on Python 3.4, thanks for reporting. 

Python 3.5 is still the recommended version for running DistAlgo.
